In [94]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Semester 3/19AI411 - Neural Networks/Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [95]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [96]:
#Check for Duplicate Values
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [97]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [98]:
#Detect the Outliers
# Outliers are any abnormal values going beyond
df['Exited'].describe()

count    10000.000000
mean         0.203700
std          0.402769
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: Exited, dtype: float64

In [102]:
""" Normalize the data - There are range of values in different columns of x are different. 

To get a correct ne plot the data of x between 0 and 1 

LabelEncoder can be used to normalize labels.
It can also be used to transform non-numerical labels to numerical labels.
"""
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df1 = df.copy()

df1["Geography"] = le.fit_transform(df1["Geography"])
df1["Gender"] = le.fit_transform(df1["Gender"])

In [103]:
'''
MinMaxScaler - Transform features by scaling each feature to a given range. 
When we normalize the dataset it brings the value of all the features between 0 and 1 so that all the columns are in the same range, and thus there is no dominant feature.
'''
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df1[["CreditScore","Geography","Age","Tenure","Balance","NumOfProducts","EstimatedSalary"]] = pd.DataFrame(scaler.fit_transform(df1[["CreditScore","Geography","Age","Tenure","Balance","NumOfProducts","EstimatedSalary"]]))

In [104]:
df1

RowNumber  CustomerId    Surname  CreditScore  Geography  Gender  \
0             1    15634602   Hargrave        0.538        0.0       0   
1             2    15647311       Hill        0.516        1.0       0   
2             3    15619304       Onio        0.304        0.0       0   
3             4    15701354       Boni        0.698        0.0       0   
4             5    15737888   Mitchell        1.000        1.0       0   
...         ...         ...        ...          ...        ...     ...   
9995       9996    15606229   Obijiaku        0.842        0.0       1   
9996       9997    15569892  Johnstone        0.332        0.0       1   
9997       9998    15584532        Liu        0.718        0.0       0   
9998       9999    15682355  Sabbatini        0.844        0.5       1   
9999      10000    15628319     Walker        0.884        0.0       0   

           Age  Tenure   Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     0.324324     0.2  0.000000       0.000000          1               1   
1     0.310811     0.1  0.334031       0.000000          0               1   
2     0.324324     0.8  0.636357       0.666667          1               0   
3     0.283784     0.1  0.000000       0.333333          0               0   
4     0.337838     0.2  0.500246       0.000000          1               1   
...        ...     ...       ...            ...        ...             ...   
9995  0.283784     0.5  0.000000       0.333333          1               0   
9996  0.229730     1.0  0.228657       0.000000          1               1   
9997  0.243243     0.7  0.000000       0.000000          0               1   
9998  0.324324     0.3  0.299226       0.333333          1               0   
9999  0.135135     0.4  0.518708       0.000000          1               0   

      EstimatedSalary  Exited  
0            0.506735       1  
1            0.562709       0  
2            0.569654       1  
3            0.469120       0  
4            0.395400       0  
...               ...     ...  
9995         0.481341       0  
9996         0.508490       0  
9997         0.210390       1  
9998         0.464429       1  
9999         0.190914       0  

[10000 rows x 14 columns]

In [105]:
df1.describe()

RowNumber    CustomerId   CreditScore     Geography        Gender  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07      0.601058      0.373150      0.545700   
std     2886.89568  7.193619e+04      0.193307      0.413765      0.497932   
min        1.00000  1.556570e+07      0.000000      0.000000      0.000000   
25%     2500.75000  1.562853e+07      0.468000      0.000000      0.000000   
50%     5000.50000  1.569074e+07      0.604000      0.000000      1.000000   
75%     7500.25000  1.575323e+07      0.736000      0.500000      1.000000   
max    10000.00000  1.581569e+07      1.000000      1.000000      1.000000   

                Age        Tenure       Balance  NumOfProducts    HasCrCard  \
count  10000.000000  10000.000000  10000.000000   10000.000000  10000.00000   
mean       0.282727      0.501280      0.304848       0.176733      0.70550   
std        0.141727      0.289217      0.248696       0.193885      0.45584   
min        0.000000      0.000000      0.000000       0.000000      0.00000   
25%        0.189189      0.300000      0.000000       0.000000      0.00000   
50%        0.256757      0.500000      0.387402       0.000000      1.00000   
75%        0.351351      0.700000      0.508749       0.333333      1.00000   
max        1.000000      1.000000      1.000000       1.000000      1.00000   

       IsActiveMember  EstimatedSalary        Exited  
count    10000.000000     10000.000000  10000.000000  
mean         0.515100         0.500441      0.203700  
std          0.499797         0.287580      0.402769  
min          0.000000         0.000000      0.000000  
25%          0.000000         0.254977      0.000000  
50%          1.000000         0.500960      0.000000  
75%          1.000000         0.746955      0.000000  
max          1.000000         1.000000      1.000000

In [107]:
# Since values like Row Number, Customer Id and surname  doesn't affect the output y(Exited).
# So those are not considered in the x values
X = df1[["CreditScore","Geography","Gender","Age","Tenure","Balance","NumOfProducts","HasCrCard","IsActiveMember","EstimatedSalary"]].values
print(X)

[[0.538      0.         0.         ... 1.         1.         0.50673489]
 [0.516      1.         0.         ... 0.         1.         0.56270874]
 [0.304      0.         0.         ... 1.         0.         0.56965435]
 ...
 [0.718      0.         0.         ... 0.         1.         0.21039009]
 [0.844      0.5        1.         ... 1.         0.         0.46442905]
 [0.884      0.         0.         ... 1.         0.         0.19091423]]


In [108]:
y = df1.iloc[:,-1].values
print(y)

[1 0 1 ... 1 1 0]


In [120]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

print(X_train)

[[0.482      1.         0.         ... 0.         1.         0.81252885]
 [0.56       0.         1.         ... 1.         1.         0.57002829]
 [0.486      1.         1.         ... 1.         1.         0.88437101]
 ...
 [0.514      0.5        1.         ... 0.         0.         0.99160525]
 [0.758      1.         0.         ... 1.         0.         0.35564166]
 [0.504      0.         1.         ... 0.         0.         0.48818972]]


In [121]:
print("Size of X_train: ",len(X_train))

Size of X_train:  8000


In [122]:
print(X_test)

[[0.824      0.5        1.         ... 1.         1.         0.53011283]
 [0.706      0.         1.         ... 1.         0.         0.75759795]
 [0.37       1.         0.         ... 0.         0.         0.31192484]
 ...
 [0.408      0.         1.         ... 1.         1.         0.06378189]
 [0.486      1.         0.         ... 1.         0.         0.33507425]
 [0.72       1.         1.         ... 0.         0.         0.49821488]]


In [123]:
print("Size of X_test: ",len(X_test))

Size of X_test:  2000


In [124]:
X_train.shape

(8000, 10)